.Optional Title
----
*Listing* Block

Use: code or file listings
----

.Optional Title
----
*Listing* Block

Use: code or file listings
----

.Optional Title
[source,perl]
----
# *Source* block
# Use: highlight code listings
# (require `source-highlight` or `pygmentize`)
use DBI;
my $dbh = DBI->connect('...',$u,$p)
    or die "connect: $dbh->errstr";
----


.Optional Title
[source,perl]
----
# *Source* block
# Use: highlight code listings
# (require `source-highlight` or `pygmentize`)
use DBI;
my $dbh = DBI->connect('...',$u,$p)
    or die "connect: $dbh->errstr";
----

.Optional Title
****
*Sidebar* Block

Use: sidebar notes :)
****


.Optional Title
****
*Sidebar* Block

Use: sidebar notes :)
****


.Optional Title
==========================
*Example* Block

Use: examples :)

Default caption "Example:"
can be changed using

 [caption="Custom: "]

before example block.
==========================


.Optional Title
==========================
*Example* Block

Use: examples :)

Default caption "Example:"
can be changed using

 [caption="Custom: "]

before example block.
==========================


.Optional Title
[NOTE]
===============================
*NOTE* Block

Use: multi-paragraph notes.
===============================


.Optional Title
[NOTE]
===============================
*NOTE* Block

Use: multi-paragraph notes.
===============================


////
*Comment* block

Use: hide comments
////


////
*Comment* block

Use: hide comments
////


++++
*Passthrough* Block
<p>
Use: backend-specific markup like
<table border="1">
<tr><td>1<td>2
</table>
++++


++++
*Passthrough* Block
<p>
Use: backend-specific markup like
<table border="1">
<tr><td>1<td>2
</table>
++++



 .Optional Title
 ....
 *Literal* Block
 
 Use: workaround when literal
 paragraph (indented) like
   1. First.
   2. Second.
 incorrectly processed as list.
 ....

.Optional Title
....
*Literal* Block

Use: workaround when literal
paragraph (indented) like
  1. First.
  2. Second.
incorrectly processed as list.
....

.Optional Title
[quote, cite author, cite source]
____
*Quote* Block

Use: cite somebody
____


.Optional Title
[quote, cite author, cite source]
____
*Quote* Block

Use: cite somebody
____