++++
<table class=cs>
++++
++++
<tr class="odd"><td class="col1">
++++
....
.Bulleted
* bullet
* bullet
  - bullet
  - bullet
* bullet
** bullet
** bullet
*** bullet
*** bullet
**** bullet
**** bullet
***** bullet
***** bullet
**** bullet
*** bullet
** bullet
* bullet

....
++++
</td><td class="col2">
++++
.Bulleted
* bullet
* bullet
  - bullet
  - bullet
* bullet
** bullet
** bullet
*** bullet
*** bullet
**** bullet
**** bullet
***** bullet
***** bullet
**** bullet
*** bullet
** bullet
* bullet

++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
.Bulleted 2
- bullet
  * bullet

....
++++
</td><td class="col2">
++++
.Bulleted 2
- bullet
  * bullet

++++
</td></tr>
++++
++++
<tr class="odd"><td class="col1">
++++
....
.Ordered
. number
. number
  .. letter
  .. letter
. number
.. loweralpha
.. loweralpha
... lowerroman
... lowerroman
.... upperalpha
.... upperalpha
..... upperroman
..... upperroman
.... upperalpha
... lowerroman
.. loweralpha
. number

....
++++
</td><td class="col2">
++++
.Ordered
. number
. number
  .. letter
  .. letter
. number
.. loweralpha
.. loweralpha
... lowerroman
... lowerroman
.... upperalpha
.... upperalpha
..... upperroman
..... upperroman
.... upperalpha
... lowerroman
.. loweralpha
. number

++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
.Ordered 2
a. letter
b. letter
   .. letter2
   .. letter2
       .  number
       .  number
           1. number2
           2. number2
           3. number2
           4. number2
       .  number
   .. letter2
c. letter

....
++++
</td><td class="col2">
++++
.Ordered 2
a. letter
b. letter
   .. letter2
   .. letter2
       .  number
       .  number
           1. number2
           2. number2
           3. number2
           4. number2
       .  number
   .. letter2
c. letter

++++
</td></tr>
++++
++++
<tr class="odd"><td class="col1">
++++
....
.Labeled
Term 1::
    Definition 1
Term 2::
    Definition 2
    Term 2.1;;
        Definition 2.1
    Term 2.2;;
        Definition 2.2
Term 3::
    Definition 3
Term 4:: Definition 4
Term 4.1::: Definition 4.1
Term 4.2::: Definition 4.2
Term 4.2.1:::: Definition 4.2.1
Term 4.2.2:::: Definition 4.2.2
Term 4.3::: Definition 4.3
Term 5:: Definition 5

....
++++
</td><td class="col2">
++++
.Labeled
Term 1::
    Definition 1
Term 2::
    Definition 2
    Term 2.1;;
        Definition 2.1
    Term 2.2;;
        Definition 2.2
Term 3::
    Definition 3
Term 4:: Definition 4
Term 4.1::: Definition 4.1
Term 4.2::: Definition 4.2
Term 4.2.1:::: Definition 4.2.1
Term 4.2.2:::: Definition 4.2.2
Term 4.3::: Definition 4.3
Term 5:: Definition 5

++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
.Labeled 2
Term 1;;
    Definition 1
    Term 1.1::
        Definition 1.1

....
++++
</td><td class="col2">
++++
.Labeled 2
Term 1;;
    Definition 1
    Term 1.1::
        Definition 1.1

++++
</td></tr>
++++
++++
<tr class="odd"><td class="col1">
++++
....
[horizontal]
.Labeled horizontal
Term 1:: Definition 1
Term 2:: Definition 2
[horizontal]
    Term 2.1;;
        Definition 2.1
    Term 2.2;;
        Definition 2.2
Term 3::
    Definition 3
Term 4:: Definition 4
[horizontal]
Term 4.1::: Definition 4.1
Term 4.2::: Definition 4.2
[horizontal]
Term 4.2.1:::: Definition 4.2.1
Term 4.2.2:::: Definition 4.2.2
Term 4.3::: Definition 4.3
Term 5:: Definition 5

....
++++
</td><td class="col2">
++++
[horizontal]
.Labeled horizontal
Term 1:: Definition 1
Term 2:: Definition 2
[horizontal]
    Term 2.1;;
        Definition 2.1
    Term 2.2;;
        Definition 2.2
Term 3::
    Definition 3
Term 4:: Definition 4
[horizontal]
Term 4.1::: Definition 4.1
Term 4.2::: Definition 4.2
[horizontal]
Term 4.2.1:::: Definition 4.2.1
Term 4.2.2:::: Definition 4.2.2
Term 4.3::: Definition 4.3
Term 5:: Definition 5

++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
[qanda]
.Q&A
Question 1::
    Answer 1
Question 2:: Answer 2

....
++++
</td><td class="col2">
++++
[qanda]
.Q&A
Question 1::
    Answer 1
Question 2:: Answer 2

++++
</td></tr>
++++
++++
<tr class="odd"><td class="col1">
++++
....
.Indent is optional
- bullet
    * another bullet
        1. number
        .  again number
            a. letter
            .. again letter

.. letter
. number

* bullet
- bullet


....
++++
</td><td class="col2">
++++
.Indent is optional
- bullet
    * another bullet
        1. number
        .  again number
            a. letter
            .. again letter

.. letter
. number

* bullet
- bullet


++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
.Break two lists
. number
. number

Independent paragraph break list.

. number

.Header break list too
. number

--
. List block define list boundary too
. number
. number
--

--
. number
. number
--

....
++++
</td><td class="col2">
++++
.Break two lists
. number
. number

Independent paragraph break list.

. number

.Header break list too
. number

--
. List block define list boundary too
. number
. number
--

--
. number
. number
--

++++
</td></tr>
++++
++++
<tr class="odd"><td class="col1">
++++
....
.Continuation
- bullet
continuation
. number
  continuation
* bullet

  literal continuation

.. letter
+
Non-literal continuation.
+
----
any block can be

included in list
----
+
Last continuation.

....
++++
</td><td class="col2">
++++
.Continuation
- bullet
continuation
. number
  continuation
* bullet

  literal continuation

.. letter
+
Non-literal continuation.
+
----
any block can be

included in list
----
+
Last continuation.

++++
</td></tr>
++++
++++
<tr class="even"><td class="col1">
++++
....
.List block allow sublist inclusion
- bullet
  * bullet
+
--
    - bullet
      * bullet
--
  * bullet
- bullet
  . number
    .. letter
+
--
      . number
        .. letter
--
    .. letter
  . number


....
++++
</td><td class="col2">
++++
.List block allow sublist inclusion
- bullet
  * bullet
+
--
    - bullet
      * bullet
--
  * bullet
- bullet
  . number
    .. letter
+
--
      . number
        .. letter
--
    .. letter
  . number


++++
</td></tr>
++++
++++
</table>
++++
